### ISSUE TITLE
camera permission issue in s8+

### ISSUE THREAD

**Issue by milanPansuriya** [nguyenhoanglam/ImagePicker#102]
Hey,
I am facing an issue with Samsung S8+ with 64 GB variant,
I had given camera permission to my app but it still displays an error message
**To continue, please give access to take pictures**   

Here I am uploading a screenshot of the error message and permissions screen
![Error message](https://i.imgur.com/AxtOTZC.jpg)
![App Info Screen](https://i.imgur.com/jEK5Df9.png)

**Comment by rutvikbhatt9** [comment]
![axtotzc](https://user-images.githubusercontent.com/31981115/51242686-a846f980-19a6-11e9-9024-4bd85bb4fe56.jpg)

**Comment by renatoarg** [comment]
Did you find a way to work this around?
