### ISSUE TITLE
Done button not showing with autoselected image from camera

### ISSUE THREAD

**Issue by ivlexey** [nguyenhoanglam/ImagePicker#103]
I'm taking picture with my camera, it's selected but there is no done button untill only image from camera selected, to attach it i need to select more pictures or close picker and call it again

**Comment by nguyenhoanglam** [comment]
I've no issue like this. Please let me know if the issue still exist.

**Comment by ivlexey** [comment]
yes it is

**Comment by nguyenhoanglam** [comment]
Hi @ivlexey,
Version 1.4.0 is now available! Please read `What's new` and check if you issue has been fixed!
