### ISSUE TITLE
getting this exception when clicking photo from camera

### ISSUE THREAD

**Issue by kuldiep** [nguyenhoanglam/ImagePicker#108]
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.         at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7908)         at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3682)         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)         at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)         at android.view.View.setFlags(View.java:12627)         at android.view.View.setVisibility(View.java:8673)         at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.showLoading(ImagePickerActivity.java:370)         at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerPresenter.loadImages(ImagePickerPresenter.java:44)         at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.getData(ImagePickerActivity.java:226)         at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.access$700(ImagePickerActivity.java:41)         at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity$7.onPermissionGranted(ImagePickerActivity.java:219)         at com.nguyenhoanglam.imagepicker.helper.PermissionHelper.checkPermission(PermissionHelper.java:34)         at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.getDataWithPermission(ImagePickerActivity.java:196)         at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.showCapturedImage(ImagePickerActivity.java:406)         at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerPresenter$2.onImageReady(ImagePickerPresenter.java:95)         at com.nguyenhoanglam.imagepicker.ui.camera.DefaultCameraModule$1.onScanCompleted(DefaultCameraModule.java:63)         at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:252)         at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:55)         at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:60)         at android.os.Binder.execTransact(Binder.java:573)

**Comment by nguyenhoanglam** [comment]
Hi @kuldiep ,
Version 1.4.0 is now available. Please check it out and close this issue if the error's gone away!
Thank you so much!
