### ISSUE TITLE
I am not getting onActivityResult in Fragment

### ISSUE THREAD

**Issue by richanshah** [nguyenhoanglam/ImagePicker#111]

**Comment by nguyenhoanglam** [comment]
You must override _onActivityResult_ method in fragment's host activity to get result in fragment

```java
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);  // You MUST have this line to be here
                                                            // so ImagePicker can work with fragment mode
}
```

**Comment by richanshah** [comment]
but  I am not inflating fragment from any activity , I have base fragment  in which i have taken Activity's context , I don't get why its skipping  result

**Comment by nguyenhoanglam** [comment]
could you send me a demo project so I would try to find out where the problem was?

**Comment by richanshah** [comment]
I am working in live project so I dont have access to share it ,Sorry about that

**Comment by richanshah** [comment]
one thing I would like to mention that i am getting
  java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
     call GlideException#logRootCauses(String) for more detail
  I am using latest version of glide,IS this related to that ?

**Comment by aruns2896** [comment]
Even I'm also having the same issue and I did override the onActivityResult method in host activity but still, it's not getting any result. Did anyone found the result then please do share?

**Comment by aruns2896** [comment]
My HomeActivity overriding _onActivityResult_ 
`@Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }`

And code for my fragment is 
`@Override
    public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        if (requestCode == 100 && resultCode == RESULT_OK && data != null)
            images = data.getParcelableArrayListExtra(Config.EXTRA_IMAGES);
        assert images != null;
        if (images.size() > 0) {
            Glide.with(context)
                    .load(images.get(0).getPath())
                    .centerCrop()
                    .into(binding.profileImage);
            Log.d(TAG, "onActivityResult: if loop" + images.get(0).getPath());
        }
        Log.d(TAG, "onActivityResult: " + images);
        super.onActivityResult(requestCode, resultCode, data);
    }`

**Comment by aruns2896** [comment]
My HomeActivity overriding onActivityResult
 ```android
@Override
protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
super.onActivityResult(requestCode, resultCode, data);
}
```

And code for my fragment is
``` android
@Override
    public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        if (requestCode == 100 && resultCode == RESULT_OK && data != null)
            images = data.getParcelableArrayListExtra(Config.EXTRA_IMAGES);
        assert images != null;
        if (images.size() > 0) {
            Glide.with(context)
                    .load(images.get(0).getPath())
                    .centerCrop()
                    .into(binding.profileImage);
            Log.d(TAG, "onActivityResult: if loop" + images.get(0).getPath());
        }
        Log.d(TAG, "onActivityResult: " + images);
        super.onActivityResult(requestCode, resultCode, data);
    }
```

**Comment by aruns2896** [comment]
@richanshah Hello, while creating ImagePicker you just need to use ImagePicker.with(MyFragment.this) instead of activity's context, I hope this will work for you. It's worked for me.

**Comment by richanshah** [comment]
Okay thanks

**Comment by aruns2896** [comment]
@richanshah Does it worked for you?
