### ISSUE TITLE
com.github.nguyenhoanglam:ImagePicker:1.3.3 image duplicate from camera android 7.1.1

### ISSUE THREAD

**Issue by arvindshishodia** [nguyenhoanglam/ImagePicker#114]
Hi I am using implementation 'com.github.nguyenhoanglam:ImagePicker:1.3.3' library and when select camera and click picture then always duplicate pictures are created. clicked image also preselected and user can't deselect this image ,below is my code-

String root = Environment.getExternalStorageDirectory().toString();
		File myDir = new File(root + "/foldername");
		ImagePicker.with(this)                         //  Initialize ImagePicker with activity or fragment context
				.setToolbarColor("#D20C0D")         //  Toolbar color
				.setStatusBarColor("#d10001")       //  StatusBar color (works with SDK >= 21  )
				.setToolbarTextColor("#FFFFFF")     //  Toolbar text color (Title and Done button)
				.setToolbarIconColor("#FFFFFF")     //  Toolbar icon color (Back and Camera button)
				.setProgressBarColor("#D20C0D")     //  ProgressBar color
				.setBackgroundColor("#ffffff")      //  Background color
				.setMultipleMode(true)              //  Select multiple images or single image
				.setFolderMode(false)                //  Folder mode
				.setShowCamera(true)                //  Show camera button
				.setFolderTitle("Albums")           //  Folder title (works with FolderMode = true)
				.setImageTitle("Gallery")         //  Image title (works with FolderMode = false)
				.setDoneTitle("Done")               //  Done button title
				.setLimitMessage("You can select upto 10 images in one go")    // Selection limit message
				.setMaxSize(10)                     //  Max images can be selected
				.setSelectedImages(images)          //  Selected images
				.setAlwaysShowDoneButton(true)      //  Set always show done button in multiple mode
				.setRequestCode(100)                //  Set request code, default Config.RC_PICK_IMAGES
				.setKeepScreenOn(true)//  Keep screen on when selecting images
.start();

**Comment by nguyenhoanglam** [comment]
@arvindshishodia I really apprecicate your contribution to my library! 
However, at the moment, I'm so busy so that I don't have time to review and test your PR. I'll check it later and release new version if it works correctly. 

Once again, thank you so much!

**Comment by etman55** [comment]
i have the same issue Android 5
