### ISSUE TITLE
Failed to create image file

### ISSUE THREAD

**Issue by demash1** [nguyenhoanglam/ImagePicker#115]
When targetSdkVersion is 29 there is issue with toast "Failed to create image file"

**Comment by ParryPatel021** [comment]
Yes, I am also facing the same problem while running my app in Android Q and has targetSdkVersion 29

**Comment by mido89** [comment]
i'm also facing same issue ???

**Comment by aruns2896** [comment]
Anyone got any solution cause my application is live and having this issue backing my application?

**Comment by mido89** [comment]
> Anyone got any solution cause my application is live and having this issue backing my application?

you can use this tag in manifest file  
 <application
        android:requestLegacyExternalStorage="true"

**Comment by nguyenhoanglam** [comment]
Hi guys,
Version 1.4.0 is now available! Please read `What's new` and check if you issue has been fixed!
