### ISSUE TITLE
Image not loaded in android 10

### ISSUE THREAD

**Issue by DevFatani** [nguyenhoanglam/ImagePicker#117]
**Android 10 - One UI 2.0**
![Screenshot_20191231-152729](https://user-images.githubusercontent.com/14845813/71623312-a5134080-2bec-11ea-809f-96eef06c705b.jpg)
![Screenshot_20191231-152733](https://user-images.githubusercontent.com/14845813/71623313-a5134080-2bec-11ea-9296-33fc02c804a1.jpg)

**Comment by nguyenhoanglam** [comment]
@DevFatani I don't have Android 10 device yet. So, I've tested the lib on the emulator and it works! I suggest you to try this fix [https://github.com/bumptech/glide/issues/3896](url). Please tell me if you solve the problem!

**Comment by DevFatani** [comment]
@nguyenhoanglam thanks, that solve the problem but temporary as mentioned in this [article](https://medium.com/@sriramaripirala/android-10-open-failed-eacces-permission-denied-da8b630a89df)
