### ISSUE TITLE
Correctly work android 4 and higher versions?

### ISSUE THREAD

**Issue by maxotov** [nguyenhoanglam/ImagePicker#12]
Hi! I want to know, did you try to test your library for any android 4 or high device? Correctly it wok for any device? Thank you.

**Comment by nguyenhoanglam** [comment]
The library works well from API 15 or higher version but Android N as reported in [issue #9](https://github.com/nguyenhoanglam/ImagePicker/issues/9)

**Comment by maxotov** [comment]
Did you test on Android 6 api 23 too? When open gallery do you check permissions? And on android N what api level version? This is latest android version?

**Comment by nguyenhoanglam** [comment]
The library checks permissions when running on API 23 or higher. 
Android N is the upcoming version 7.0 . There is an error when capturing image and I'm trying to fix this bug.

**Comment by maxotov** [comment]
Thank you for quick response
