### ISSUE TITLE
It's not loading the images after updating to 1.4.1 or 1.4.0

### ISSUE THREAD

**Issue by ma7moudAziz** [nguyenhoanglam/ImagePicker#122]
Hi @nguyenhoanglam,
Thanks for this awesome library it is very useful for me, but recently after I update the module to the latest version it stops working, it opens but it keeps loading without showing the folders.

and here how I am implementing the ImagePicker: 

`

ImagePicker.with(myFragment!!)
                .setToolbarColor("#3F51B5")
                .setStatusBarColor("#000000")
                .setToolbarTextColor("#FFFFFF")
                .setToolbarIconColor("#FFFFFF")
                .setProgressBarColor("#4CAF50")
                .setBackgroundColor("#FFFFFF")
                .setCameraOnly(false)
                .setMultipleMode(true)
                .setFolderMode(true)
                .setShowCamera(false)
                .setFolderTitle("Folder title")
                .setImageTitle("Image title")
                .setDoneTitle(getString(R.string.submitText))
                .setLimitMessage(getString(R.string.reachImagesLimitErrorMessage))
                .setMaxSize(100)
                .setAlwaysShowDoneButton(true)
                .start()

`

And to be noted I am using android and Kotlin v.1.3.72.

And thanks in advance,
Regards.

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz which Android version are you using? Please try with another version to check if it works. If it also not working, then let me know!

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam ,
Yes, it only not working on android 9, it's working just fine with android 7,8 and 10.
Regards.

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam,
Kindly assist me here, your assistance will be grateful and to be noted the new version 1.4.2 did not fix the issue.
Regards.

**Comment by robiky** [comment]
same here please has this been fixed

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz  @robiky it sounds strange! I've just test on Samsung device (Android 9) and it works! Can you guys show me the app's log?

**Comment by robiky** [comment]
It's has no error log and it's android 10

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam, thanks for your efforts but actually there is no errors showing in logs, but here are a part of the logs just after I click on the open camera function:

W/HiTouch_HiTouchSensor: depended package hiTouch does n't exist!
2020-06-08 09:56:28.566 4541-6034/com.infosysta.mobile.mfjsdp I/HiTouch_HiTouchSensor: HiTouch restricted: system app HiTouch don't exist.
2020-06-08 09:56:28.567 4541-6034/com.infosysta.mobile.mfjsdp D/HiTouch_PressGestureDetector: onAttached, package=com.infosysta.mobile.mfjsdp, windowType=1, mHiTouchRestricted=true
2020-06-08 09:56:28.766 4541-4674/com.infosysta.mobile.mfjsdp V/FA: Connection attempt already in progress
2020-06-08 09:56:28.801 4541-4674/com.infosysta.mobile.mfjsdp V/FA: Activity resumed, time: 105521
2020-06-08 09:56:28.825 4541-4685/com.infosysta.mobile.mfjsdp D/OpenGLRenderer:   HWUI Binary is  enabled
2020-06-08 09:56:28.828 4541-4541/com.infosysta.mobile.mfjsdp W/InputMethodManager: startInputReason = 1
2020-06-08 09:56:29.098 4541-4685/com.infosysta.mobile.mfjsdp E/ion: ioctl c0044901 failed with code -1: Invalid argument
2020-06-08 09:56:29.098 4541-4685/com.infosysta.mobile.mfjsdp I/chatty: uid=10158(com.infosysta.mobile.mfjsdp) RenderThread identical 1 line
2020-06-08 09:56:29.099 4541-4685/com.infosysta.mobile.mfjsdp E/ion: ioctl c0044901 failed with code -1: Invalid argument
2020-06-08 09:56:29.099 4541-4685/com.infosysta.mobile.mfjsdp D/OpenGLRenderer: endAllActiveAnimators on 0xc0322200 (IndicatorView) with handle 0xc5596530
2020-06-08 09:56:29.221 4541-4674/com.infosysta.mobile.mfjsdp V/FA: Connection attempt already in progress
2020-06-08 09:56:29.226 4541-4674/com.infosysta.mobile.mfjsdp V/FA: Connection attempt already in progress
2020-06-08 09:56:29.227 4541-4674/com.infosysta.mobile.mfjsdp D/FA: Connected to remote service
2020-06-08 09:56:29.231 4541-4674/com.infosysta.mobile.mfjsdp V/FA: Processing queued up service tasks: 4
2020-06-08 09:56:34.345 4541-4674/com.infosysta.mobile.mfjsdp V/FA: Inactivity, disconnecting from the service
2020-06-08 09:56:38.185 4541-4541/com.infosysta.mobile.mfjsdp D/ViewRootImpl[DashboardActivity]: surface should not be released
2020-06-08 09:56:38.272 4541-4541/com.infosysta.mobile.mfjsdp I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time.

I hope it's helpful.
Best Regards.

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz so you means the lib keeps showing loading progress after taking a photo or on the first load?

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam, yes the lib keep showing the loading on the first load, and on my last comment I mentioned when open the camera I meant open the gallery I am using the image picker to get images from the gallery.

And thank you.
Regards.

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz  @vjjustin Just tested again and it still works! I think you guys please send me a screen record and the device name that you use for more detail!

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam, Thank you for your efforts the device I am testing on is Huawei Y6 Prime 2019.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13847691/84383979-f0973500-abf5-11ea-8c90-101aadbbc34c.gif)

**Comment by shanzeehashmi** [comment]
Hello @nguyenhoanglam , please? Same issue for me.
When opening the gallery it is just showing a loading symbol and is stuck there.

**Comment by shanzeehashmi** [comment]
Hello @nguyenhoanglam , please? Same issue for me.
When opening the gallery it is just showing a loading symbol and is stuck there, in real device having android 9

**Comment by nguyenhoanglam** [comment]
Hi all, ultil now I can't debug this issue on my android 9 device. So I suggest you guys debug my lib's source to find out the issue:
- Look at the ```ImageFileLoader``` class -> inner class ```ImageLoadRunnable``` that is responsible for loading images. 
- Check if ```listener.onImageLoaded(images)``` is called (means loaded images success)
- If success, look at ```ImagePickerViewModel``` class to check if the success callback is handle in ```onImageLoaded``` of ```fetchImages``` method.
- Then in ```FolderFragment``` class (if you use folderMode = true), check if the result with ```CallbackStatus.SUCCESS``` is returned here:
```java    
viewModel?.result?.observe(viewLifecycleOwner, Observer {
      handleResult(it)
 })
```
I hope you guys help me fix this bug. Thank a lot!

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam,
I find the issue it seems that it's been stuck in this loop:

> do {

                    val id = cursor.getLong(cursor.getColumnIndex(MediaStore.Images.Media._ID))
                    val name = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DISPLAY_NAME))
                    val path = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DATA))
                    val bucketId = cursor.getLong(cursor.getColumnIndex(MediaStore.Images.Media.BUCKET_ID))
                    val bucketName = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.BUCKET_DISPLAY_NAME))
                    val file = makeSafeFile(path)
                    if (file != null && file.exists()) {
                        val image = Image(id, name, path, bucketId, bucketName)
                        images.add(image)
                    }
                } while (cursor.moveToPrevious())

cursor.moveToPrevious() is always true.

and here is an image showing you some variables if it helps:
![Screen Shot 2020-06-15 at 11 04 32 AM](https://user-images.githubusercontent.com/13847691/84632793-170be780-aef8-11ea-8cd4-c1f01974bcea.png)

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz I followed your debug guide, made some changes in the loop block. But I still not sure that it'll fix the issue.

So I built an example apk and hope you will install it to check if the issue is gone! Please download the file in the link below:
[https://drive.google.com/file/d/1V-XAAIRcfxWuFICO2PKeCuWTTbuO4wrz/view?usp=sharing](url)

**Comment by KishanViramgama** [comment]
application works good in Nokia 6.1 plus android 10  @nguyenhoanglam

**Comment by nguyenhoanglam** [comment]
@KishanViramgama which version is your Nokia running?
Did your device have this issue before?

**Comment by KishanViramgama** [comment]
i have checked first time of this version works fine @nguyenhoanglam

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam, 
Thanks for the shared APK, I've tried it but the issue keeps occurring.

To be noted I've tried this on multiple phones it's working just fine the issue is only occurring on Huawei devices whatever the OS version, @shanzeehashmi, and @vjjustin can you please confirm the devices used for testing.

Also to be noted version 1.3.2 it's working fine even on the Huawei devices if this might help.

Best Regards.

**Comment by shanzeehashmi** [comment]
i had tested in android 9.0 in asus. The issue is occuring in this device
as far my concern,, else i have tested in other version with real device,
their it is fine

**Comment by ma7moudAziz** [comment]
Thanks, @shanzeehashmi for the response.

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz Are you sure `cursor.moveToPrevious()` is always true? Or maybe the cursor is iteratoring all images and it has not reached the end yet.

Does the debuger reach `listener.onImageLoaded(images)` line?

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam,
yes here there are 2 points drove me to this conclusion as follows:

- At first glance, I never reach the breaking point set on this listener.onImageLoaded(images).

- And second, the device had only 114 images, and if you check the image I've sent I was already at the iteration number 140, which exceeds the maximum number of the images in the device.

The weird thing here that if I use Samsung or HTC or Sony devices even if the OS version was 9 the gallery opens normally with no issues but this only occurs for Huawei devices in my case and Asus as the case of @shanzeehashmi.

I know it's hard for you to fix such an issue, especially that it's not replicable locally for you (I've been there) but I'll try to help you as much as I can.

Best Regards.

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam,
I debugged it again to make sure, I notice that all the images returned are the same, for ex: all images in the array had the same name, the same id which means it's stuck on the first image as it seems load previous image function it's not really getting the previous image.
Regards.

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz Followed your description about cursor loop exceeds the maxium number of images. I've replaced the cursor's while loop by for index loop:
```java
for (i in 0 until cursor.count) {
      cursor.moveToPosition(i)
      val id = cursor.getLong(idColumn)
      val name = cursor.getString(nameColumn)
      ...
}
```

This may prevent the loop exceeds 140 images.

About the 140 number of images instead of 114 images as you mentioned, I think there're some hiden images in the device that you don't know

After all, I rebuilt a new apk that using for index loop. Please install again and tell me the result!
[https://drive.google.com/file/d/1kHJRRqmJG88R6zjSzyn5nw2XNFQblG-A/view?usp=sharing](url)

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam,
Still the same not working, and about the images, this was where I stop the debug but it actually stays at the loop, and as I mentioned in the second comment all the images were with the same name and the same id, as it was returning the same image again and again and again.

But the weird thing here is this should've worked, but it still not can you please send me the source code of the second project to debug the For loop to check whats is really happening?

Regards.

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam,
Any update on this?.

Regards.

**Comment by 9574595538** [comment]
**Problem is here**
 var images = arrayListOf<Image>()
 if (cursor.moveToLast()) {
                do {
                    val id = cursor.getLong(cursor.getColumnIndex(MediaStore.Images.Media._ID))
                    val name = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DISPLAY_NAME))
                    val path = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DATA))
                    val bucketId = cursor.getLong(cursor.getColumnIndex(MediaStore.Images.Media.BUCKET_ID))
                    val bucketName = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.BUCKET_DISPLAY_NAME))
                    val file = makeSafeFile(path)
                    if (file != null && file.exists()) {
                        val image = Image(id, name, path, bucketId, bucketName)
                        images.add(image)
                    }
                } while (cursor.moveToPrevious())
            }


**Replace your code with**

 var images = arrayListOf<Image>()
val temp = ArrayList<Image>(cursor.count)
            if (cursor.moveToFirst()) {
                do {
                    if (Thread.interrupted()) {
                        return
                    }
                    val id = cursor.getLong(cursor.getColumnIndex(MediaStore.Images.Media._ID))
                    val name = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DISPLAY_NAME))
                    val path = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.DATA))
                    val bucketId = cursor.getLong(cursor.getColumnIndex(MediaStore.Images.Media.BUCKET_ID))
                    val bucketName = cursor.getString(cursor.getColumnIndex(MediaStore.Images.Media.BUCKET_DISPLAY_NAME))
                    val file = makeSafeFile(path)
                    if (file != null && file.exists()) {
                        var image: Image? = null
                        if (id != null && name != null && path != null && bucketId != null && bucketName != null) {
                            image = Image(id, name, path, bucketId, bucketName)
                            if (image != null)
                                images.add(image)
                        }
                    }
                } while (cursor.moveToNext())
            }
            if (images == null) {
                images = java.util.ArrayList()
                images!!.clear()
                images!!.addAll(temp)
            }
            cursor.close()
            listener.onImageLoaded(images)
            Thread.interrupted()

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz Thanks to @reenasavaliya21, I changed the loop code and built another apk. Please check it out!
[https://drive.google.com/file/d/1qMdhFTHCJA7X-WVeKyk-XH9A5ZHdnpWg/view?usp=sharing](url)

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam,
Thank you for the shared APK, this one is working perfectly for me.
Thank you so much for your efforts.
Best Regards.

**Comment by nguyenhoanglam** [comment]
@ma7moudAziz Finally, together we solved it!

One more step, the previous apk's code is not optimized. So I'v updated the code and hope you will test it once again!

[https://drive.google.com/file/d/1PmVrP4Mslu4_X5wXduxuAv9D1HwemaWu/view?usp=sharing](url)

**Comment by vjjustin** [comment]
Hi,
Just tested the apk. This works for me too. This is Xiaomi redmi phone.
Thanks for the great work.

Sorry couldn't test/reply earlier because was busy with a major update on
my app.

**Comment by reenasavaliya21** [comment]
hey @nguyenhoanglam  i am using your imagepikcer dependncy and i am facing issue,  I was not able to show my most recent photos on top. it show images into Ascending order....please help me to handle this issue.

**Comment by nguyenhoanglam** [comment]
@reenasavaliya21 Please try this example apk. If it works as your expectation, I will release a new version soon!

**Comment by ma7moudAziz** [comment]
Hi @nguyenhoanglam ,
Thank you so much, it's working now.
I will close this for now as it's been resolved.
Best Regards.

**Comment by reenasavaliya21** [comment]
Yes It's working well now.,Thank you.
