### ISSUE TITLE
We need to support Android 11

### ISSUE THREAD

**Issue by Sayed-Shalan** [nguyenhoanglam/ImagePicker#124]
android:requestLegacyExternalStorage="true" is a workaround. so can we migrate to scoped storage ASAP ?. Thank you.

**Comment by nguyenhoanglam** [comment]
I've tested on the Android 11 emulator and it works! 

If you have an Android 11 device, please test it and let me know the result.

**Comment by mrNoolas** [comment]
For my emulator it seems to only work with albums that are owned by this app. Pictures in the gallery or elsewhere cannot be opened in Android 11 for me.

**Comment by ArchangelXu** [comment]
Just built a library to support Android 11. Tested on Android 10 (device) and Android 11 (Simulator):
https://github.com/ming-xi/MXMediaPicker

**Comment by frared358** [comment]
@nguyenhoanglam it is still not working on Android11 devices but working on emulator..

**Comment by nguyenhoanglam** [comment]
@frared358 v1.5.3 just has been released. Check it out!
