### ISSUE TITLE
Failed to open the camera

### ISSUE THREAD

**Issue by Sayed-Shalan** [nguyenhoanglam/ImagePicker#125]
For version 1.4.3 . when click camera icon it said "Failed to open the camera". Android 10 Huawei

**Comment by sonalirawat** [comment]
For version 1.4.3. I am facing the same issue on every device on clicking the camera button

**Comment by rakeshr-anvd** [comment]
Version 1.4.3 shows "Failed to open camera" on Android version 7,8 and 10

**Comment by 24Lathiya** [comment]
I am also facing same problem. just let me know i any have idea to fix it.

**Comment by sonalirawat** [comment]
no Idea, Just change the library. Use another library for camera and
gallery images

**Comment by Aisalkyn** [comment]
Still did not fixed this bug?

**Comment by MahmoudAbunaji** [comment]
Same issue any solution ?

**Comment by sasij** [comment]
I had the same problem on Android 11 and it was fixed adding this snipped to my AndroidManifest. Add it inside the `manifest` tag.

```xml
<queries>
  <intent>
    <action android:name="android.media.action.IMAGE_CAPTURE" />
  </intent>
</queries>
```
