### ISSUE TITLE
error: package com.nguyenhoanglam.imagepicker.activity does not exist

### ISSUE THREAD

**Issue by gcatak** [nguyenhoanglam/ImagePicker#126]
It gives this error in build time.

`error: package com.nguyenhoanglam.imagepicker.activity does not exist`

How can I solve it?

**Comment by gcatak** [comment]
Any answer?

**Comment by nguyenhoanglam** [comment]
@gcatak Did you completely follow the installation guide step by step?

**Comment by gcatak** [comment]
Yes of course, I added glide library to gradle files. Then it gives this error. Additionally, I migrated to AndroidX
There was no problem before change.

**Comment by gcatak** [comment]
Could you check this, please?

https://stackoverflow.com/questions/63204640/error-package-com-nguyenhoanglam-imagepicker-activity-does-not-exist

My question in SO.

**Comment by nguyenhoanglam** [comment]
I suggest you to do below step:
- Remove Image Picker dependency in app build.gradle
- Comment all Image Picker usages and remove all imports in your code
- Clean, invalidate caches and restart
- Add Image Picker dependency again, sync, uncomment and import Image Picker again.

**Comment by gcatak** [comment]
```
import com.nguyenhoanglam.imagepicker.activity.ImagePicker;
import com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity;

```

Problematic import statements in my code. Is usage correct?

**Comment by nguyenhoanglam** [comment]
Maybe your import path is outdate. The two import path should be here
[https://github.com/nguyenhoanglam/ImagePicker/tree/master/imagepicker/src/main/java/com/nguyenhoanglam/imagepicker/ui/imagepicker](url)

**Comment by gcatak** [comment]
I am using Java, not Kotlin. Should I use this library?

**Comment by nguyenhoanglam** [comment]
This lib works well with Java project. You can use it without any problem!

**Comment by gcatak** [comment]
I changed mygradle files to this library. 

https://github.com/esafirm/android-image-picker

Now, it is working without any problem.
