### ISSUE TITLE
Selected images can't come in result activity

### ISSUE THREAD

**Issue by maxotov** [nguyenhoanglam/ImagePicker#13]
I have two activity one of them list of item and one adding item activity. In adding item activity i call your ImagePickerActitvity to select images. Then ImagePickerActivity when i select images and push add button, in my activity doesn't come any response. This is problem occured, i guess when in adding item activity press back button to list of item activity. Then i open adding activity again, this problem occured.

**Comment by maxotov** [comment]
log when i open imagePickerActivity
`08-18 11:47:22.164 28278-28278/kz.tamur.shopmanage I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
08-18 11:47:22.171 28278-28278/kz.tamur.shopmanage D/ProgressBar: setProgress = 0
08-18 11:47:22.171 28278-28278/kz.tamur.shopmanage D/ProgressBar: setProgress = 0, fromUser = false
08-18 11:47:22.171 28278-28278/kz.tamur.shopmanage D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 100
08-18 11:47:22.234 28278-28278/kz.tamur.shopmanage E/RecyclerView: No adapter attached; skipping layout
08-18 11:47:22.257 28278-28278/kz.tamur.shopmanage D/WritingBuddyImpl: getCurrentWritingBuddyView() `
log when i press to add button
08-18 11:49:01.343 28278-28278/kz.tamur.shopmanage D/WritingBuddyImpl: getCurrentWritingBuddyView()

**Comment by nguyenhoanglam** [comment]
Thanks for reporting this bug. I've just fixed it and please wait for the next release!

**Comment by Baawaaji** [comment]
I am also facing similar problem here is my log:
 E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/IMG_20160808_235807.jpg
                                                                               : open failed: ENOENT (No such file or directory)

**Comment by nguyenhoanglam** [comment]
@Baawaaji This error occurred when capturing image, right? Did you run on emulator or device?

**Comment by Baawaaji** [comment]
This error occured during selecting image or capturing image and I testing it on emulator too and its gave me same errors.

**Comment by nguyenhoanglam** [comment]
@Baawaaji @maxotov Version 1.0.3 is now available. Please check out if the bug is solved!

**Comment by Aintsoa** [comment]
I still have the same problem, when I click on the button add in "ImagePickerActivity" my application closes. Can you help me!

**Comment by maxotov** [comment]
Aintsoa, try call ImagePickerActivity by traditional way.
`Intent intent = new Intent(this, ImagePickerActivity.class);

intent.putExtra(ImagePickerActivity.INTENT_EXTRA_MODE, ImagePickerActivity.MODE_MULTIPLE);
intent.putExtra(ImagePickerActivity.INTENT_EXTRA_LIMIT, 10);
intent.putExtra(ImagePickerActivity.INTENT_EXTRA_SHOW_CAMERA, true);
intent.putExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES, images);
intent.putExtra(ImagePickerActivity.INTENT_EXTRA_TITLE, "Tap to select");

startActivityForResult(intent, REQUEST_CODE_PICKER);`

**Comment by Rainer-Lang** [comment]
@maxotov @Baawaaji @Aintsoa Does this bug still exists in the newest version? Please check it. Thanks.
@nguyenhoanglam Maybe close this?
