### ISSUE TITLE
Android 10 scoped storage

### ISSUE THREAD

**Issue by jayantur13** [nguyenhoanglam/ImagePicker#132]
I'm migrating to scoped storage,before migration everything was fine with legacy storage.But,while using scoped storage I'm not getting image path.

**Comment by ArchangelXu** [comment]
Just built a library to support Android 11. Tested on Android 10 (device) and Android 11 (Simulator):
https://github.com/ming-xi/MXMediaPicker

**Comment by dsounded** [comment]
+1, this one is really relevant
