### ISSUE TITLE
Photo flipped 90 degrees

### ISSUE THREAD

**Issue by benny831228** [nguyenhoanglam/ImagePicker#139]
Thanks for the library!

I use version 1.5.1
Why is the photo flipped 90 degrees after taking a photo?

**Comment by buttonDeveloper** [comment]
have the same issue. pls help

**Comment by nguyenhoanglam** [comment]
@benny831228 @buttonDeveloper 
- I've just released v1.5.2 with a rotation fix for api 29 and higher. Please check it out!
- For api 28 and lower, I don't implement a fix because I don't have a real device to test.

Thanks!
