### ISSUE TITLE
Need More Help ....

### ISSUE THREAD

**Issue by YasirAmeen** [nguyenhoanglam/ImagePicker#14]
Hey nguyenhoanglam,

Thank you for all the help you provided me. 

I want to ask one thing if you don't mind.
When taking picture using your library from camera, its first appear in gallery then we select it to be use.

Now i want it to be like , " after taking picture from camera its selected in activity results"

more clearly, like facebook does when take picture from camera.

Millions of thanks

**Comment by nguyenhoanglam** [comment]
You can custom my library to meet your expectation!
In ImagePickerActivity, modify onActivityResult method like this:

```java
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == Constants.REQUEST_CODE_CAPTURE) {
            if (resultCode == RESULT_OK) {
                if (fileTemp != null && fileTemp.exists()) {
                    MediaScannerConnection.scanFile(this,
                            new String[]{fileTemp.getAbsolutePath()}, null,
                            new MediaScannerConnection.OnScanCompletedListener() {
                                @Override
                                public void onScanCompleted(String path, Uri uri) {
                                    Log.v("MediaScanWork", "file " + path
                                            + " was scanned successfully: " + uri);
                                    
                                    Image image = new Image(0,"",path,false);
                                    ArrayList<Image> images = new ArrayList<Image>();
                                    images.add(image);
                                    
                                    Intent data = new Intent();
                                    data.putParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES, images);
                                    setResult(RESULT_OK, data);
                                    finish();
                                   // getDataWithPermission();
                                }
                            });
                }
            }
        }
    }
```

Please feel free to ask me any question!

**Comment by Rainer-Lang** [comment]
@YasirAmeen Is your question answered? If yes - please close this issue.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam I think the question is answered.

**Comment by Rajabsk** [comment]
Hi,
My project is capturing image from the camera and set it in ImageView. Later, it has to be uploaded to the database. Image picker from the gallery is working fine but am getting an error with camera intent. Can you please help me with correct code.

My code is as follows.

For Camera Intent:
Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
startActivityForResult(intent, 1);
------------------
  protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
 if (requestCode == 1) {
 featuredImages_gallery = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
                Uri uri = Uri.fromFile(new File(featuredImages_gallery.get(0).getPath()));
                Picasso.with(AddPropertiesActivity.this).load(uri).into(img_gallery);     
isFeaturedGallery = true;     

 }

---------
Image Picker from gallery code:

  ImagePicker.create(this)
                .folderMode(true)
                .folderTitle("Folder")
                .imageTitle("Tap to select")
                .multi()
                .limit(5)
                .showCamera(false)
                .imageDirectory("Camera")
                .start(REQUEST_FEATURED_PICKER_GALLERY);
-------------------
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
if (requestCode == REQUEST_FEATURED_PICKER_GALLERY) {
            if (resultCode == Activity.RESULT_OK && data != null) {
                featuredImages_gallery = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
                Uri uri = Uri.fromFile(new File(featuredImages_gallery.get(0).getPath()));
                Picasso.with(AddPropertiesActivity.this).load(uri).into(img_gallery);
isFeaturedGallery = true;
}

}
}

Uploading data to server:
if (isFeaturedGallery) {
            request.addParameter("place_gallery_image[]", featuredImages_gallery);
        }
