### ISSUE TITLE
Android 11 - Can't see images from SD Card

### ISSUE THREAD

**Issue by Pocus76** [nguyenhoanglam/ImagePicker#140]
Hi, 

I'm having a problem using your library with the latest version (1.5.1) on Android 11, the medias from the SD Card aren't shown and therefore I'm not able to select those files.

Is there a way to fix it ? 

Thanks for your help and for the library

**Comment by nguyenhoanglam** [comment]
@Pocus76 Please check out v1.5.3 and let me know if it works!

**Comment by Pocus76** [comment]
@nguyenhoanglam Hi, I tried today using the latest version, unfortunately I'm still unable to see the pictures from my SD card.
Is there anything to set in AndroidManifest.xml or in ImagePickerConfig ? 
Thanks!

**Comment by nguyenhoanglam** [comment]
@Pocus76 plz check v.1.6.2.
