### ISSUE TITLE
Empty Gallery

### ISSUE THREAD

**Issue by VozNick** [nguyenhoanglam/ImagePicker#143]
Hi,
I use library v1.5.2
on Huawei P smart+ (android 9) says the gallery is empty.
* all permissions are granded
* gallery does have photos
* tested on many phones (samsung, pixel, xiaomi), made all same steps,  - gallery shows files, exept on huawei

thanks

**Comment by nguyenhoanglam** [comment]
@VozNick  @twnth you got the issue on Huawei device too? I don't have a Huawei device so I can not debug to check this issue. 
So, I would be grateful if you guys could fork this lib and help me debug it. Thanks in advance!

**Comment by dattran-pt19** [comment]
@nguyenhoanglam Mình cũng bị bug tương tự trên Android 11, không hẳn Android 11 nào cũng bị nhưng bạn có thể debug ở máy ảo thử xem. Mình config 1 máy ảo Pixel 3a 1080x2220 Android 11.0 (R - API 30 - x86) thì có xảy ra lỗi

**Comment by dattran-pt19** [comment]
In fetchImages function have Exception "BucketName must not be null"

**Comment by nguyenhoanglam** [comment]
@dattran-pt19 tui vừa test trên máy ảo như ông nói, chạy vẫn load được hình. ông debug rồi coi thử có thể fix cho nó không lỗi BucketName bị null được ko? xong thì ông tạo PR lên giúp tui.

cám ơn nhiều nhé!

**Comment by dattran-pt19** [comment]
@nguyenhoanglam Case này là do lỗi dữ liệu của máy thì phải, máy ảo t chạy sẽ bị lỗi khi có ảnh nằm trong sdk_gphone_x86_arm. Chắc khi ảnh nằm ở vị trí không thuộc folder nào như thế cursor k index ra được nên trả ra bucketName null. Ông chỉ cần check nếu bucketName bị null thì continue vòng While là được

**Comment by nguyenhoanglam** [comment]
@dattran-pt19 cái này chắc nhờ ông fix giúp t quá. chứ giờ t ko biết nó lỗi ở dòng nào mà check null. ông fix xong rồi test coi nó ok ko? làm phiền ông giúp tui nhé!

**Comment by dattran-pt19** [comment]
@nguyenhoanglam Tui vừa tạo PR rồi nhé

**Comment by nguyenhoanglam** [comment]
@dattran-pt19 t có comment trong PR đó. ông coi thử.

**Comment by nguyenhoanglam** [comment]
@VozNick @twnth Please upgrade to v1.5.3 to help me check if the bug has been fixed.
Thank @dattran-pt19 for helping me out with this issue! 🙌 🙌

**Comment by twnth** [comment]
@nguyenhoanglam 
Sorry for the late confirmation and Thank you for your quick resolution, it has fixed!!!
i love you man
