### ISSUE TITLE
Not working in android 33

### ISSUE THREAD

**Issue by aerocube-tech** [nguyenhoanglam/ImagePicker#147]

**Comment by jateengadhiya** [comment]
![WhatsApp Image 2022-10-18 at 10 17 14 AM](https://user-images.githubusercontent.com/18609131/196337846-2ef5d340-56bd-489e-b0d2-1adc59375c0c.jpeg)

Please find the attached Screenshot. It working fine on android 31. But when it switch to android 33. This show error on reading media file. Please check and verify.

**Comment by ZoeVale** [comment]
Hello any idea? It's seam a permission problem

**Comment by nguyenhoanglam** [comment]
Hi guys, I don't have any device running api 33. So I test it on emulator but do not see any permission issue. 
It would be nice if you guys help me debug the error while I'm earning money to buy new device. Thanks a lot!

**Comment by ZoeVale** [comment]
hi @nguyenhoanglam about test this issue you can start application accept permission (if you have any) and then go to settings of your app and remove permission.

You notice that permission are for you library not for the application so you can't resolve the issue

**Comment by aerocube-tech** [comment]
Got Solution. There is new permission for Android Tiramisu (Android 33) for reading device images. 

`
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />


<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />


<uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />


<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
                 android:maxSdkVersion="32" />

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                 android:maxSdkVersion="29" />`

**Comment by aerocube-tech** [comment]
`
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />


<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />


<uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />


<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
                 android:maxSdkVersion="32" />

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                 android:maxSdkVersion="29" />`

**Comment by aerocube-tech** [comment]
please check the @[link](https://developer.android.com/training/data-storage/shared/media#storage-permission)

**Comment by petrstetka** [comment]
@aerocube-tech How did you solve it? I tried add READ_MEDIA_IMAGES permission into AndroidManifest and runtime asked on this permission but I am still getting blank screen like on screenshot [above](https://github.com/nguyenhoanglam/ImagePicker/issues/147#issuecomment-1281811442)

**Comment by aerocube-tech** [comment]
@petrstetka This is how you set the permission in manifest.

<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="32"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="29" tools:replace="android:maxSdkVersion"/>

and later you have to fork this library into your project and update permission request relevant sdk version. If still not get it please contact me on hello@aerocube.tech

**Comment by nguyenhoanglam** [comment]
@aerocube-tech @jateengadhiya @ZoeVale @petrstetka Version 1.5.5 is available now. Please help me check it out and let me know if the bug is gone. 

Sorry for letting you guys wait for so long... 😅

**Comment by zoelounge** [comment]
Ho @nguyenhoanglam i try in the afternoon. 
At a moment I resolve problems with a tricks. 

On OnCreate I call my fun "checkPermission" so if there's some problems I resolve. 

But it doesn't run if user go to steering's and toggle the permissions.

**Comment by nguyenhoanglam** [comment]
@zoelounge You can try v1.5.5 without using any tricks. 
```READ_EXTERNAL_STORAGE``` has been removed on Android 13. That's why the permission request always fails. So, I've added ```READ_MEDIA_IMAGES``` to support Android 13 or higher. Please check it out!

**Comment by zoelounge** [comment]
Ok I'll try it on afternoon. 
Thanks so much for your job. 👍

**Comment by petrstetka** [comment]
@nguyenhoanglam Version 1.5.5 works for me on Android 13. Thank you! 
In my opinion, this issue can be closed and be considered as resolved.
