### ISSUE TITLE
CAMERA Permission

### ISSUE THREAD

**Issue by borjaseijo** [nguyenhoanglam/ImagePicker#155]
Hi. 
When you click on the camera icon in order to take a photo it's neccesary that you also request the CAMERA permissions because if you have declared this permission in the manifest and you don't request it, the library crashes, because it can be set to FALSE in Android system.

I hope that I can help you with this information.

Best regards and thank you for your great job!

**Comment by nguyenhoanglam** [comment]
@borjaseijo I will check this case. Thanks for your contribution!

**Comment by nguyenhoanglam** [comment]
Please upgrade to v1.6.1 to check if the bug is fixed. Also, help me play around with new config options and let me know if you found a
Thank guy!
