### ISSUE TITLE
Is there any way to handle the callback from toolbar back icon

### ISSUE THREAD

**Issue by Anirban2022** [nguyenhoanglam/ImagePicker#156]
I want to handle the back icon and system back callback, is it currently supported?

**Comment by nguyenhoanglam** [comment]
You mean you want to handle back press (e.g to show confirm dialog) instead of exitting the picker by default?

**Comment by Anirban2022** [comment]
Yes correct.

**Comment by nguyenhoanglam** [comment]
Got it! Maybe it should be in the next release.

**Comment by nguyenhoanglam** [comment]
@Anirban2022 when implementing back handler callback feature, I find that I want to dispay a confirm dialog using app context (not library context), the dialog will not be shown because the library view is on top of app view. so could you give me an idea for this case?
