### ISSUE TITLE
Camera related question

### ISSUE THREAD

**Issue by slowmo0037** [nguyenhoanglam/ImagePicker#157]
Hello everyone, wanted to ask if this lib should work like this.
When you click on camera button and camera activity starts: You take picture and then click ok it takes me back to Images activity it's not returning the image Uri like when you have isCameraMode = true or when you select image from Gallery.

Am I missing something or this is just a bug?

If anyone can point me in right direction how to accomplish this would be much appreciated.

@nguyenhoanglam It would be good if I can get response from the boss :) you've done really good job here.

**Comment by nguyenhoanglam** [comment]
@slowmo0037 After captured, the image is shown in the picker activity, not return the uri because I think we have nothing to do with that uri. I want to know what will you do with that uri?

**Comment by slowmo0037** [comment]
> @slowmo0037 After captured, the image is shown in the picker activity, not return the uri because I think we have nothing to do with that uri. I want to know what will you do with that uri?

Well I'm building a photo editing app and the logic in other libraries i tried is exactly like this: when you go to pick your photo from camera you take the photo and takes you to the editor activity not picker activity again, it means it returns the uri of the photo in an intent to next activity (photo get's auto selected like when you have isCameraMode = true) that is correct logic for editing photo apps, but if you use this library for only Gallery app and have camera set like you did it's 100% correct logic.

**Comment by nguyenhoanglam** [comment]
@slowmo0037 s
Got it! If you set ```isMultiSelectMode``` to ```false```, you could achieve the same logic (the picker closes and returns an uri ). However, that only works for selecting image. I'll apply the same logic for capturing mode in the next release.

**Comment by slowmo0037** [comment]
> @slowmo0037 s Got it! If you set `isMultiSelectMode` to `false`, you could achieve the same logic (the picker closes and returns an uri ). However, that only works for selecting image. I'll apply the same logic for capturing mode in the next release.

Thank you @nguyenhoanglam  you are amazing with all you do :) I'll mark this as closed and wait for the next release.

**Comment by nguyenhoanglam** [comment]
@slowmo0037 v1.6.2 is now available. Could you help me verify if the bug is fixed and play around with other updates (preview mode, image sorting). If you find out any bugs, please let me know. I really appreciate it!

**Comment by slowmo0037** [comment]
Thank you so much, will do it right now and let you know how everything goes.

**Comment by nguyenhoanglam** [comment]
@slowmo0037 how did it go my friend?
