### ISSUE TITLE
it's possible to show folders like a Gallery ?

### ISSUE THREAD

**Issue by Hitexroid** [nguyenhoanglam/ImagePicker#16]
it's possible to show folders like a GalleryApp ?

right now images in recyclerview sorted by date added!

**Comment by nguyenhoanglam** [comment]
No, it's not possible to show folder. I would consider to add this feature to this library.

**Comment by boss1088** [comment]
@nguyenhoanglam Hi, I create a pull request. Here you can enable folder mode with
ImagePicker.create(this)
                .folderMode(true)
or adding to intent
intent.putExtra(ImagePickerActivity.INTENT_EXTRA_FOLDER_MODE, true);

**Comment by Hitexroid** [comment]
Thank you so much ! can you send your updated library to my gmail account ?
i really need it :+1: 

[sadeq.hitex@gmail.com](mailto:sadeq.hitex@gmail.com)

**Comment by Hitexroid** [comment]
@nguyenhoanglam

i created item_folder.xml and copy your xml code, into res/layout
when i use your code , compiler returns this Error :

> ..\res\layout\item_folder.xml:2: error: Error: No resource found that matches the given name (at 'id' with value '@id/selector').
..\res\layout\item_folder.xml:22: error: Error: No resource found that matches the given name (at 'id' with value '@id/name').
..\res\layout\item_folder.xml:34: error: Error: No resource found that matches the given name (at 'id' with value '@id/num').
