### ISSUE TITLE
Imagepicker doesn't return result on second call.

### ISSUE THREAD

**Issue by codevalley** [nguyenhoanglam/ImagePicker#17]
I am using imagepicker activity in the following way.
```
ImagePicker.create(ComposeActivity.this)
           .single() 
           .showCamera(true) 
           .start(INTENT_REQUEST_GET_IMAGES); 
```
This same structure is used in a few activities.
When I call this for the first time, it works perfectly. On second call, (either from the same activity or different one), the `onActivityResult()` is not called. It works again when you kill and start the app.
Tested on multiple devices running Marshmallow.

**Comment by nguyenhoanglam** [comment]
@codevalley  I've fixed this bug already but I'm getting problem when releasing the next version to Github as I mentioned [here](https://github.com/nguyenhoanglam/ImagePicker/issues/15) . Please wait until I find the solution!

**Comment by codevalley** [comment]
Sure thing!
