### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by maxotov** [nguyenhoanglam/ImagePicker#22]
Hi! I noticed exception, when after take picture i press ok button, and app stop running and write below: 
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage()' on a null object reference
                                                                         at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(ImagePickerActivity.java:545)
                                                                         at java.lang.Thread.run(Thread.java:818)`

**Comment by maxotov** [comment]
until i added code to check to null object handler
`if(handler!=null) {
                message = handler.obtainMessage();
                message.what = Constants.FETCH_COMPLETED;
                message.sendToTarget();
            }`
seems exception is gone.

**Comment by mansoorriaaz** [comment]
Hai, how to do it? could please explain. thx

**Comment by maxotov** [comment]
Hi, it is mine temporary solution, if you want to try then firstly add library as module to app and change this line of this file ImagePickerActivity.java:545 which i added. But i guess seems author of library decided this problem, we expect author response. Till i didn't update last updating library version.
