### ISSUE TITLE
in android 6 not function to check permission to take photo

### ISSUE THREAD

**Issue by maxotov** [nguyenhoanglam/ImagePicker#23]
In android 6 sdk 23 when press button to take photo app stop running and show exception in the log that doesn't permission to take picture

**Comment by nguyenhoanglam** [comment]
Maybe you did not grant permission when start picker activity at the first time. You can click "OK" on the snackbar to show permission request dialog. However I'm going to fix this bug right now.

Thanks!

**Comment by maxotov** [comment]
Yes, in first time when i go to ImagePickerActivity show me gialog to agree use system gallery. I press ok. But i press camera icon button in the toolbar app show me exception about camera permission. I guess it seems you did only permission to use system gallery.
