### ISSUE TITLE
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

### ISSUE THREAD

**Issue by jhay143pee** [nguyenhoanglam/ImagePicker#27]
compileSdkVersion 21
 buildToolsVersion "21.1.2"  
 minSdkVersion 19
 targetSdkVersion 21
 versionCode 12
 versionName "2.1"

Hello there,

I have a project , and i want to use it on SDK 21, is it possible? I really love this library, its so easy to use.

**Comment by nguyenhoanglam** [comment]
OK. I'll check your problem soon!

**Comment by andhie** [comment]
it is because your version is too low.
Widget.Material.Button.Colored only appear on API 23 but you are compiling against API 21
https://developer.android.com/reference/android/R.style.html#Widget_Material_Button_Colored

**Comment by nguyenhoanglam** [comment]
@jhay143pee You should compile the library with API 23 as @andhie mentioned. 
Version 1.1.1 is available now. Please check it out!

**Comment by jhay143pee** [comment]
I would love too, but my project max is 21 only. If im going to upgrade it to 23, i will be having problems in HTTPPOSTREQUEST and need to migrate a lot of things.

Thanks anyway guys , i think ill just create my own library.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Close this?
