### ISSUE TITLE
The height of photos in album comes 'match parent'?

### ISSUE THREAD

**Issue by fansays** [nguyenhoanglam/ImagePicker#29]
Both by quick call or using traditional Intent, the situation in the following pic occurs. (Which did not happen when I was using your 1.0.1 version. )
![Screenshot](https://cloud.githubusercontent.com/assets/11610348/18410290/5715371c-7790-11e6-9164-4a521f321212.jpg)

**Comment by Rainer-Lang** [comment]
@fansays Is this still in the newest version? If not - please close this issue.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam I think this could really be closed...
