### ISSUE TITLE
Picking an image using camera or camera images is not showing in imageView.

### ISSUE THREAD

**Issue by YasirAmeen** [nguyenhoanglam/ImagePicker#3]
I am using your library but having some issues like, i am unable to set picture to the ImageView by taking an image from camera.

**Comment by nguyenhoanglam** [comment]
Did you check whether you successfully received the camera image path?

**Comment by YasirAmeen** [comment]
Yes i received camera path successfully. I checked in toast

**Comment by nguyenhoanglam** [comment]
And how do you load that image path to ImageView?

**Comment by YasirAmeen** [comment]
Here it is, 
`_img_one.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View view) {

				ImagePicker.create(MyDialog.this)
						.single()
						.showCamera(true)
						.origin(images)
						.start(REQUEST_CODE_PICKER_1);
			}
		});*`


and in onActivityResult..
`@Override
	protected void onActivityResult(int requestCode, int resultCode, Intent data) {
		if (requestCode == REQUEST_CODE_PICKER_1 && resultCode == RESULT_OK && data != null) {
			images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
			final StringBuffer stringBuffer = new StringBuffer();
			for (int i = 0, l = images.size(); i < l; i++) {
				stringBuffer.append(images.get(i).getPath() + "\n");
			}


//			_img_one.post(new Runnable() {
//				@Override
//				public void run() {
//
//					Picasso.with(MyDialog.this).load(new File(stringBuffer.toString().trim())).into(_img_one);
//
//				}
//			});

			Picasso.with(MyDialog.this).load(new File(stringBuffer.toString().trim())).into(_img_one);
			Toast.makeText(MyDialog.this, stringBuffer.toString(), Toast.LENGTH_SHORT).show();
		}

	}`

**Comment by nguyenhoanglam** [comment]
I've check your problem and I suggest 2 solutions for you:

1. If you use Picasso, you have to add resize() and centerCrop() methods:
```java
Picasso.with(this).load(new File(images.get(0).getPath())).resize(200,200).centerCrop().into(imageView);
```

2. If you use Glide (recommended):
```java
Glide.with(this).load(images.get(0).getPath()).into(imageView);
```

In my opinion, this error occured because the image's dimension is too large for the ImageView to display. So you should resize the image to the same size with the ImageView's. However, if you use Glide (which already embeded in ImagePicker module) to load image as the above code, the problem is solved easily!

**Comment by AstonBraham** [comment]
@nguyenhoanglam 's library is working really fine..

I think that you should choose just one image to display in your ImageView..

Not multiple

Try this and let us  know


```


    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == REQUEST_CODE_PICKER && resultCode == RESULT_OK && data != null) {
            ArrayList<Image> images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);

                 try
                  {
                      String lien = images.get(0).getPath();
                      Glide.with(this).load(lien).into(mImageView);
                  }         
                catch(Exception e)
                {
                    Log.e("MyActivity", e.getMessage());
                }
        }
    }

```

**Comment by YasirAmeen** [comment]
Thanks mate, 

Your Code is working perfect.
Great Library you made, just thumps fro you :+1: 

Regards
Yasir Ameen
