### ISSUE TITLE
crash when take with real camera asus zenfone 4c KITKAT OS

### ISSUE THREAD

**Issue by joShinichi** [nguyenhoanglam/ImagePicker#35]
hay, i use your library and that's awesome...
but when after take the picture in real camera asus zenfone 4c,
the crash occurred...

please help..
thanks
best regards

**Comment by nguyenhoanglam** [comment]
please show me the error description so I know how to fix!

**Comment by joShinichi** [comment]
there is no error, in logcat...what should i do ?
iam using usb debuger for running my apps

**Comment by joShinichi** [comment]
10-05 17:40:25.935 11201-11201/com.example.jo_shinichi1.telegramtestgallery E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
10-05 17:40:26.025 11201-11201/com.example.jo_shinichi1.telegramtestgallery E/IMGSRV: :0: PVRDRMOpen: TP3, ret = 49
10-05 17:40:26.035 11201-11201/com.example.jo_shinichi1.telegramtestgallery E/IMGSRV: :0: PVRDRMOpen: TP3, ret = 52
10-05 17:40:26.035 11201-11201/com.example.jo_shinichi1.telegramtestgallery E/IMGSRV: :0: PVRDRMOpen: TP3, ret = 53
10-05 17:40:26.035 11201-11201/com.example.jo_shinichi1.telegramtestgallery E/IMGSRV: :0: PVRDRMOpen: TP3, ret = 53
10-05 17:40:26.045 11201-11201/com.example.jo_shinichi1.telegramtestgallery E/IMGSRV: :0: PVRDRMOpen: TP3, ret = 53
10-05 17:40:26.055 11201-11201/com.example.jo_shinichi1.telegramtestgallery E/IMGSRV: :0: PVRDRMOpen: TP3, ret = 55


here the error sir, but im not sure about this,,,

**Comment by nguyenhoanglam** [comment]
Please try to build project with sdk 23 or above!

**Comment by joShinichi** [comment]
my sdk version is 24 sir...

**Comment by tushar09** [comment]
I am facing the same problem. My error logcat is RecyclerView: No adapter attached; skipping layout

**Comment by Rainer-Lang** [comment]
@joShinichi @tushar09 Could you please test it with the newest version? 
@nguyenhoanglam Maybe this issue could be closed.
