### ISSUE TITLE
Camera Error

### ISSUE THREAD

**Issue by tushar09** [nguyenhoanglam/ImagePicker#36]
I am using 1.1.2 and the camera error is still there. When I try to take picture from camera the app crashes.  How to solve it? I am trying it into API 17

**Comment by nguyenhoanglam** [comment]
Please show me the error description in log console.

**Comment by arkty** [comment]
@nguyenhoanglam https://github.com/nguyenhoanglam/ImagePicker/pull/45
Probably this is the same crash. NullPointerException. Confirmed on Nexus 5X Android 7.0.

**Comment by Rainer-Lang** [comment]
@tushar09 @arkty @nguyenhoanglam Download newest version and check again - or close this issue maybe?

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Close this issue?
