### ISSUE TITLE
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]

### ISSUE THREAD

**Issue by jookovjook** [nguyenhoanglam/ImagePicker#39]
Hello!
When trying to use the library with 2 different apps, getting this error during installation:
pkg: /data/local/tmp/com.company.application
Failure [INSTALL_FAILED_CONFLICTING_PROVIDER]
As i know, the use is connected to authorities. But i really can't get how to cope with it.
Please, can you help me? Thanks

**Comment by alfaro28** [comment]
Hi, we had the same problem with some of our apps, the solution we found is to define a string in your strings.xml like this:

<string name="shared_file_provider">com.nguyenhoanglam.imagepicker.provider.YOURPROJECTNAME</string>

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Close this?

**Comment by nguyenhoanglam** [comment]
@jookovjook @alfaro28 Please update to the newest version. Thanks!
