### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gcatak** [nguyenhoanglam/ImagePicker#41]
It is not working? and it is not clear.

How  can I set imageview this
`ArrayList<Image> images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);`
??

Why do not you explain?? It is the most important thing and explaining should not be hard but you did not explain why?

**Comment by nguyenhoanglam** [comment]
You can display image into ImageView as below:
```java
Image image = images.get(0);  // in this case, show the first image
Glide.with(this).load(image.getPath()).into(imageView);
```java

**Comment by Rainer-Lang** [comment]
This is out of this library scope. Showing images with paths in ImageView is basic.
@nguyenhoanglam I think you could close this issue.
