### ISSUE TITLE
Images stay selected when you restart ImagePickerActivity

### ISSUE THREAD

**Issue by funriser** [nguyenhoanglam/ImagePicker#42]

**Comment by nguyenhoanglam** [comment]
If you want to unselect all pictures, just simply *do not call the origin()
method* when start picker activity. For example:

ImagePicker.create(this)
            .multi()
            .start(REQUEST_CODE_PICKER);



Best regards,



*Hoang Lam Nguyen*

Android Developer


Mobile: 0987 857 818

Skype: hoanglamvn90

URL: *https://about.me/hoanglamvn90 <https://about.me/hoanglamvn90>*

2016-11-23 3:10 GMT+07:00 funriser <notifications@github.com>:
