### ISSUE TITLE
Let minSdkVersion=14 please!

### ISSUE THREAD

**Issue by belinwu** [nguyenhoanglam/ImagePicker#51]

**Comment by Rainer-Lang** [comment]
@belinwu minSdk 15 should be really enough.... https://developer.android.com/about/dashboards/index.html
Do you really need 14?!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Close this - or maybe it's possible to use minSdk 14?

**Comment by belinwu** [comment]
@Rainer-Lang Thanks for your reply. Currently minSdk 15 is enough.

**Comment by Rainer-Lang** [comment]
@belinwu Then - could you close this issue please. :-)

**Comment by Rainer-Lang** [comment]
Thanks.
