### ISSUE TITLE
I want to get the picture directly after taking picture from the camera.

### ISSUE THREAD

**Issue by sagarnayak** [nguyenhoanglam/ImagePicker#52]
if i am selecting the option to take a picture from camera and then it just take the picture and then i have to select the picture from the gallery. so i want to just get the picture returned after i take the picture from the camera. i dont want to select the same picture after i take that picture. please suggest a solution.

**Comment by Rainer-Lang** [comment]
@sagarnayak For me it's working in the sample app.
@nguyenhoanglam Close this issue?

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang If you use CameraOnly mode, the image is returned immediately as @sagarnayak expected. 

However, if you tap the camera button (on the toolbar, CameraOnly mode = FALSE), the captured image will not be selected automatically. So @sagarnayak asked me to make it auto selected. I'll consider this option if I find it useful and convinient for user.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Ah ok, I understand. Then YES - this is really a big PLUS for your lib! :-)

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang You think it's a really nice feature, don't you?

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Of course. If the user wants a picture from camera - he just wants THIS and finish. I would use this feature!

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang That's great! I will update this feature in the next release.
Thank you so much!

**Comment by nguyenhoanglam** [comment]
Hi guys,
Version 1.4.0 is now available. Please check it out and close this issue if the error's gone away!
Thank you so much!
