### ISSUE TITLE
Crashes the Samsung S4 Mini camera after taking the photo in 1.1.3, android version 4.2.2 (catlog incl.)

### ISSUE THREAD

**Issue by edindubai** [nguyenhoanglam/ImagePicker#53]
It crashes the Samsung S4 Mini camera after taking the photo in 1.1.3 android version 4.2.2. The viewfinder continues to be active for about 4 seconds more after pressing the take photo button and then finally freezes. The picture (from point of capture not where viewfinder freezes) arrives in the gallery though but only after "Unfortunately, Camera has stopped" message, it is a guaranteed crash on every try. (works ok on S6 edge). I crashed it 3 times and can see 3 fatal exceptions in the attached log cat but logs are new to me, so unsure of cause/fix.
[logcat.txt](https://github.com/nguyenhoanglam/ImagePicker/files/633521/logcat.txt)

**Comment by edindubai** [comment]
I found a more recent modified version of this library which doesn't have the above crash here: https://android-arsenal.com/details/1/4618

**Comment by djdance** [comment]
thanks, edindubai

**Comment by Rainer-Lang** [comment]
@edindubai @djdance Want to try the newest version? Or maybe close this issue?
@nguyenhoanglam Close this issue?
