### ISSUE TITLE
Info about selecting a single photo 

### ISSUE THREAD

**Issue by mba3gar** [nguyenhoanglam/ImagePicker#56]
Please i want to select just one single photo and return it's result in ImageView instead of returning it's path 

the main issue is that i can't replace the array of images or strings in a single one can you please assist ? 

Thank you :)

**Comment by nguyenhoanglam** [comment]
If you want to select only one photo, use single mode:
```java
ImagePicker.create(this)
                .folderMode(true) // set folder mode (false by default)
                .folderTitle("Folder") // folder selection title
                .imageTitle("Tap to select") // image selection title
                .single() // single mode
                .showCamera(true) // show camera or not (true by default)
                .imageDirectory("Camera")   // captured image directory name ("Camera" folder by default)
                .origin(images) // original selected images, used in multi mode
                .start(REQUEST_CODE_PICKER); // start image picker activity with request code
```

Then onActivityResult, use Glide (or Picasso) to load the path into ImageView:

```java
Glide.with(this).load(path).into(imageView);
```

**Comment by Rainer-Lang** [comment]
@mba3gar Just use Glide like @nguyenhoanglam wrote. It's really straight forward.
@nguyenhoanglam Good answer. I think you could close this issue.
