### ISSUE TITLE
Activity Toolbar Color?

### ISSUE THREAD

**Issue by hak24** [nguyenhoanglam/ImagePicker#57]
Is there any way to chage activity primary color from pink to any other?

**Comment by sinadalvand** [comment]
you should go to external library and find "Imagepicker" 
open that and go to res folder and find "toolbar" in layout after that you just need to edit this code:

android:background="#your color code"

**Comment by Rainer-Lang** [comment]
Is it right now possible that the toolbar color gets the primary app theme color?

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang it's impossible in this version. I will update this feature in the next release.
Thanks very much!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Thank you for this great lib and your time developing it!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam This is not in v1.2.1, right?

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang I've not found a solution for this feature yet. If you have any solution, please let me know.
Thank you!

**Comment by Rainer-Lang** [comment]
Maybe have a look at "esafirm".
