### ISSUE TITLE
Images stay selected

### ISSUE THREAD

**Issue by kalkrishnan** [nguyenhoanglam/ImagePicker#6]
Images once selected stay selected after i exit from my app. How do i set them to deselect after i click add?

**Comment by nguyenhoanglam** [comment]
I don't know what you really want. Please describe more detail!

**Comment by kalkrishnan** [comment]
Say I go into my gallery using this and select a few images and click add which closes the gallery. Later if i go back into my gallery using this, the images I had selected earlier stay selected. This seems like an issue to me, shouldn't the selections clear once I have clicked add?

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam I could confirm this. Maybe it would be good to have a parameter: keep selected images OR unselect images - something like this.

**Comment by nguyenhoanglam** [comment]
@kalkrishnan If you don't want to keep images selected, do not pass selected images parameter. Please update to version 1.2.0 which has more features!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Write this in the readme? I think this is a really good thing to know.
