### ISSUE TITLE
Change DONE button title

### ISSUE THREAD

**Issue by djdance** [nguyenhoanglam/ImagePicker#60]
Please add .doneTitle() for the case of another language

**Comment by RurouniX** [comment]
Hi.

Add this `<string name="done">YOUR STRING</string>` in your string.xml to override the string .

**Comment by nguyenhoanglam** [comment]
I named it "setDoneTitle()" just to synch with others methods. It's not important , isn't it?

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Great! Thanks. Included in the next version?

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang what do you mean? :)

**Comment by Rainer-Lang** [comment]
Will be the "setDoneTitle(@StringRes int doneTitleRes)" method available in the next version?

**Comment by nguyenhoanglam** [comment]
Ah. Sure!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam It's already included....so this could be closed?
