### ISSUE TITLE
Anything about Proguard?

### ISSUE THREAD

**Issue by Rainer-Lang** [nguyenhoanglam/ImagePicker#67]
Is there anything to consider using Proguard and your lib?

**Comment by nguyenhoanglam** [comment]
I'm not good at Proguard. I think you can use Glide's Proguard for my lib!

**Comment by Rainer-Lang** [comment]
OK. I'll try your lib with Proguard - and report the result here. Please let this issue open - and I'll also change your readme to add the result. OK?

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam For Proguard there is nothing special needed. 
Closing this issue.
