### ISSUE TITLE
I need an "Intent".

### ISSUE THREAD

**Issue by Rainer-Lang** [nguyenhoanglam/ImagePicker#69]
For my purpose I need to create an ```Intent``` - not only start the ImagePicker.
I'm using RxActivityResult https://github.com/VictorAlbertos/RxActivityResult to streamline the result.

May I ask to add this?

**Comment by Rainer-Lang** [comment]
see here: https://github.com/nguyenhoanglam/ImagePicker/pull/70

**Comment by nguyenhoanglam** [comment]
I'll consider this option when I complete other features!

**Comment by Rainer-Lang** [comment]
Perfect, thanks.

**Comment by Rainer-Lang** [comment]
I could use your ImagePicker right in this moment, when you release a new version where I could get an ```Intent```.
I'm also open for snapshots to test - if you want.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Some news? If there is a version to test.... :-)

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang If you need an Intent to start ImagePickerActivity, I will add a getIntent() method in the Builder for you to use. Here is my code:
```java
static class ActivityBuilder extends Builder {
        private Activity activity;

        public ActivityBuilder(Activity activity) {
            super(activity);
            this.activity = activity;
        }

        @Override
        public void start() {
            Intent intent = getIntent();
            if (!config.isCameraOnly()) {
                activity.startActivityForResult(intent, Config.RC_PICK_IMAGES);
            } else {
                activity.overridePendingTransition(0, 0);
                activity.startActivityForResult(intent, Config.RC_PICK_IMAGES);
            }
        }

        @Override
        public Intent getIntent() {
            Intent intent;
            if (!config.isCameraOnly()) {
                intent = new Intent(activity, ImagePickerActivity.class);
                intent.putExtra(Config.EXTRA_CONFIG, config);
            } else {
                intent = new Intent(activity, CameraActivty.class);
                intent.putExtra(Config.EXTRA_CONFIG, config);
                intent.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION);
            }
            return intent;
        }
    }
```

Please let me know what you think about this modification.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Looks good 👍

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang I'm coding other features. So you've to wait for a long time until I release a new version!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam That's no problem. BUT I'm very curious :-) - so could you please make a new ticket with a checkmark-list of features you want to develop so I see whats coming and the progress?

**Comment by nguyenhoanglam** [comment]
- Done: 
   1. Auto select image after capturing.
   2. Return an Intent for manually starting picker.
- Coding:
   3. Auto get main app color (toolbar, status bar...) . I've tried many solutions but still not succeeded. 
   4. Avatar mode (as you sugessted). This feature is take a long time to finish beacause I've to create my own camera screen. I don't know if I could achieve it or not. 

Maybe, after finishing the 3rd feature, I will make a release. Thanks!

**Comment by Rainer-Lang** [comment]
for 4. look here: https://github.com/natario1/CameraView/ Maybe you could add it for this feature - only additional of course?

**Comment by Rainer-Lang** [comment]
for 3. This could be solved in another Github lib project.

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang send me the link please!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam 3. Sorry this is a misunderstanding. I think it COULD have been solved in another project. I don't know which, but I could do a search...

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang OK. I'll try!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam I tried v1.2.1 and it's working great. 👍 
Closing this issue.
