### ISSUE TITLE
Change the activity title

### ISSUE THREAD

**Issue by benoffi7** [nguyenhoanglam/ImagePicker#7]
Hi! I want to change the title of the activity. Can you add a extra parameter ?

Thanks!

**Comment by nguyenhoanglam** [comment]
I'll add this feature in the next update. But now you can manually change activity title by this way:
1. Download the library and import it to your project as a module
2. Go to the module resource's strings.xml and change title, message or any string you wants

**Comment by benoffi7** [comment]
Thanks!

2016-08-15 23:26 GMT-03:00 Nguyen Hoang Lam <notifications@github.com>:

**Comment by nguyenhoanglam** [comment]
@benoffi7 Version 1.0.3 is available. Please check out new feature!

**Comment by benoffi7** [comment]
Wow!!! Thanks a lot!!!

2016-08-19 3:41 GMT-03:00 Nguyen Hoang Lam <notifications@github.com>:
