### ISSUE TITLE
Suggestion: Camera overlay

### ISSUE THREAD

**Issue by Rainer-Lang** [nguyenhoanglam/ImagePicker#71]
I want to put an overlay in front of the camera - like this one: https://i.stack.imgur.com/NszHG.png
A round half transparent overlay - because my users should make a profile image - and I show round profile images in my app.

Maybe we could use something like setForeground(Drawable)

**Comment by nguyenhoanglam** [comment]
Good idea! It's should be an option in next version!

**Comment by Rainer-Lang** [comment]
Great.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam May I ask for the progress?
