### ISSUE TITLE
Fragment onActivityResult not called, Activity onActivityResult is called

### ISSUE THREAD

**Issue by koeks525** [nguyenhoanglam/ImagePicker#75]
Hi,

I just dicovered this library now. I want to show an image picker, where the user selects their desired image. When implementing this library, I see that the Fragment's onActivityResult is not called - instead, the Activity where the fragment is hosted, gets its onActivityResult. Here is the code on my fragment: 

`ImagePicker.Builder builder = ImagePicker.with(getActivity())                        
                        .setToolbarColor("#212121")         
                        .setStatusBarColor("#000000")       
                        .setToolbarTextColor("#FFFFFF")     
                        .setToolbarIconColor("#FFFFFF")    
                        .setProgressBarColor("#4CAF50")     
                        .setBackgroundColor("#212121")      
                        .setCameraOnly(false)               
                        .setMultipleMode(false)              
                        .setFolderMode(true)                
                        .setShowCamera(true)               
                        .setFolderTitle("Albums")           
                        .setImageTitle("Galleries")        
                        .setDoneTitle("Done")              
                        .setMaxSize(10)                    
                        .setSavePath("HomeNET")         
                        .setSelectedImages(imageList)          
                        ;
                builder.start();`

Is there a way of making this library call the Fragment's onActivityResult and not the Hosting Activity's onActivityResult?? 

Thanks.

**Comment by nguyenhoanglam** [comment]
In Activity's onActivityResult(), remember to add super.onActivityResult(requestCode, resultCode, data) method, so Fragment's onActivityResult() will be called

```java
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (requestCode == Config.RC_PICK_IMAGES && resultCode == RESULT_OK && data != null) {
        ArrayList<Image> images = data.getParcelableArrayListExtra(Config.EXTRA_IMAGES);
        // do your logic here...
    }
    super.onActivityResult(requestCode, resultCode, data);
}
```

**Comment by koeks525** [comment]
Thank you so much for the tip :)

**Comment by Rainer-Lang** [comment]
@koeks525 If your question is answered - please close this issue.
