### ISSUE TITLE
 ActivityNotFoundException 7.0

### ISSUE THREAD

**Issue by SocialSpammer** [nguyenhoanglam/ImagePicker#76]
android.content.ActivityNotFoundException: Unable to find explicit activity class {marketingfor.instagram/com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity}; have you declared this activity

**Comment by nguyenhoanglam** [comment]
Could you tell me how you got this error?

**Comment by Rainer-Lang** [comment]
@SocialSpammer Could you give a bit more feedback - or could this issue be closed?

**Comment by nguyenhoanglam** [comment]
Hi @SocialSpammer ,
Version 1.4.0 is now available. Please check it out and close this issue if the error's gone away!
Thank you so much!
