### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Rainer-Lang** [nguyenhoanglam/ImagePicker#77]
I designed special dialogs with images extra for asking the user BEFORE the Android system permission dialog.
I would like to use them - even with your lib. Could this be done, maybe in future?

**Comment by nguyenhoanglam** [comment]
I think there is no need to to that. Many popular app like Google Photos still using the default permission dialog.

**Comment by Rainer-Lang** [comment]
Yeah - but it's a Google app so the people "trust" this app more. I have an explanation dialog for every other permission.
