### ISSUE TITLE
Custom text for Max select Images

### ISSUE THREAD

**Issue by ziakhan421** [nguyenhoanglam/ImagePicker#78]
How to change the custom text for max images are selected. You have to give option to change this.  Because this will also be translated.

**Comment by nguyenhoanglam** [comment]
Maybe you should fork my lib and add a translation file for your language (strings.xml file). Then create a pull request.So, in the nexr version, the text is automatically selected base on your device language. 

Otherwise, I will consider this option and add it into next update.

Thanks for using my lib!

**Comment by ziakhan421** [comment]
I need this solution hurry! if you can. You have to add a static function so that the user can set this message accordingly. Thanks in advance.

**Comment by Rainer-Lang** [comment]
@ziakhan421 If you need it fast - make fast a PR.

**Comment by ziakhan421** [comment]
@Rainer-Lang  I don't know what to do. Can you help me in this regard.

**Comment by ziakhan421** [comment]
@nguyenhoanglam When will the new version uploaded with solving my issue?

**Comment by IsaiasSantana** [comment]
@ziakhan421 add to your strings.xml: <string name="imagepicker_msg_limit_images">%d your_language</string>

**Comment by IsaiasSantana** [comment]
add to your strings.xml: "<string name="imagepicker_msg_limit_images">%d  your_limit_language</string>"

**Comment by IsaiasSantana** [comment]
Add to you strings.xml ` <string name="imagepicker_msg_limit_images">%d you_limit_language</string>`

**Comment by nguyenhoanglam** [comment]
@ziakhan421 version 1.2.1 is available. check it out to custom limit selection text!

**Comment by ziakhan421** [comment]
@nguyenhoanglam Thanks dear.
