### ISSUE TITLE
Support for a wakelock

### ISSUE THREAD

**Issue by MileyHollenberg** [nguyenhoanglam/ImagePicker#80]
In our app we have a wakelock enabled to make sure the phone doesn't turn off whilst the user is using the app (and has put it asside for a little while). When the user closes the app via the home button this wake lock is released and allows Android to go to sleep again according to the user's setting. 

The problem is that this is handled per activity and we don't have any power over the activity created by this plugin, how can we get a wake lock to function whilst this image picker is open and have it be released when the user closes the app from this library's activity? It's a small change that a user will actually notice this but for the sake of consistency we do want to implement this feature throughout our entire app.

**Comment by zezioen** [comment]
@nguyenhoanglam Yes that would be perfect

**Comment by nguyenhoanglam** [comment]
@zezioen OK. I'll add this option in the next version. Please keep following this lib to be notified of a new update!

**Comment by nguyenhoanglam** [comment]
@zezioen Version 1.2.1 is available. Please check it out with new method ```setKeepScreenOn()```. Let me know if you're satisfied with this update.

**Comment by zezioen** [comment]
Cool, do you think I could easily place the library in the Xamarin Binding project and create a temporary 1.2.1 there? We're working on a Xamarin Project so I can't really test it on native Android.

**Comment by nguyenhoanglam** [comment]
I've not worked on Xamarin yet. But I think if you're working on hybrid app, you can make a call to native methods to start ImagePicker. Then pass the result back to Xamarin via callback.

**Comment by zezioen** [comment]
You're correct on that but you do need a binding library in order to be able to access the native calls, I'm gonna have a look and see if I can just swap out the AAR file and re-build the binding (could you maybe provide me with a direct link for that file, haven't really got the hang of Android Studio yet to do it easily myself)

**Comment by nguyenhoanglam** [comment]
@zezioen Have you build the AAR file yet?

**Comment by zezioen** [comment]
Oh damn, sorry I totally forgot (a colleague of mine fixed our issue in a different way at the same time you were working on it). I'll see what I can do tonight.

**Comment by zezioen** [comment]
I've tried to build the project and it build successfully but I don't see any AAR anywhere in my build directories. I also don't even see the regular jar file (the only jar I found is mockable-android-26.jar which is 26Mb and most likely the wrong jar. How do I go about building an AAR?

**Comment by nguyenhoanglam** [comment]
Here is AAR file. After importing aar file, you also need to add RecyclerView and Glide library to your gradle file because aar file does not contain others library

[](https://drive.google.com/open?id=0B68_WLJadG_JM0VQNnJ5UTdwb1E)

**Comment by zezioen** [comment]
I was able to build the binding library succesfully after updating Glide but I can't see the new setKeepScreenOn method. I'm going to open up a ticket over at https://github.com/NAXAM/imagepicker-android-binding for this linking back to this issue right here

**Comment by nguyenhoanglam** [comment]
Did you build with version 1.2.1? The android binding link above looks like the old version!

**Comment by zezioen** [comment]
I used the AAR file you provided in the comment above, that's the 1.2.1 build right?

**Comment by nguyenhoanglam** [comment]
Yes. It's 1.2.1 build!

**Comment by zezioen** [comment]
Odd, I'll try again later today, maybe the project didn't clean properly
