### ISSUE TITLE
Image replaced in camera only mode 

### ISSUE THREAD

**Issue by lingesh10** [nguyenhoanglam/ImagePicker#88]
I want to show ten file by taking pictures in recyclerview, but each time when i take picture the showing file in the recyclerview  get replaced. kindly give solution.
note: i made some temporary solution but i want permanent and optimized solution.

**Comment by nguyenhoanglam** [comment]
After taking a picture, the recyclerview will be refreshed and the captured picture will be selected automatically. You have to go to the save folder to see the captured picture.

**Comment by nguyenhoanglam** [comment]
@lingesh10 I've just  updated version 1.3.0 with Done button always visible feature. Example:
```java
ImagePicker.with(this)
           .setAlwaysShowDoneButton(true) 
```
Please check this feature and close this issue if it works. Thanks!

**Comment by lingesh10** [comment]
Dear Lam,
 Sure once I checked I will close that issue.
Thanks for the fixation.

**Comment by aruns2896** [comment]
@lingesh10 What is the code for Camera only mode???

**Comment by lingesh10** [comment]
@nguyenhoanglam Image replace in recyclerview but i can see the taken picture in the folder. thanks. But my requirement is camera only enabled and take 10 pictures and show in recyclerview, please do that change in your project it will be more helpful to others also....

**Comment by lingesh10** [comment]
@aruns2896 disable all the radiobutton and enable camera only mode..
