### ISSUE TITLE
Done menu button

### ISSUE THREAD

**Issue by codenut** [nguyenhoanglam/ImagePicker#89]
Hello,

Thank you for this very useful plugin. Is it possible to show the Done menu button even if theres no selected images?

**Comment by nguyenhoanglam** [comment]
It's not possible. I will consider your option in the next update!

**Comment by codenut** [comment]
@nguyenhoanglam It will be cool if it will be supported on the next update. Thanks!

**Comment by nguyenhoanglam** [comment]
@codenut  I've just updated version 1.3.0 with Done button always visible feature. Example:
```java
ImagePicker.with(this)
           .setAlwaysShowDoneButton(true) 
```
Please check this feature and close this issue if it works. Thanks!

**Comment by codenut** [comment]
@nguyenhoanglam awesome! It is working as expected.

Thanks!
