### ISSUE TITLE
can i select only videos and only images using this API

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [nguyenhoanglam/ImagePicker#94]
can i select only videos or only images using this API ?
if yes, what the option to set for selecting only images and for selecting only videos ?
if no, can you please add this feature.

**Comment by nguyenhoanglam** [comment]
@kpradeepkumarreddy this library only supports selecting images. you can read the guide in the Usage section here https://github.com/nguyenhoanglam/ImagePicker

**Comment by kpradeepkumarreddy** [comment]
i'm using glide 3.7.0 and this library is using glide 4.7.0 . I'm getting some errors related to glide drawable.

**Comment by nguyenhoanglam** [comment]
I think you should upgrade to Glide 4.7.0 and review its usage.

**Comment by kpradeepkumarreddy** [comment]
upgraded glide to 4.7.0 and it is working now.
