### ISSUE TITLE
SELECT ALL option, to select all the images in a folder

### ISSUE THREAD

**Issue by jerinamathews** [nguyenhoanglam/ImagePicker#96]
Is there any option to enable "select all feature", to select all the images in a folder.

**Comment by jerinamathews** [comment]
Please add it to the next release. "Select all" if the images in the folder are less than max count or "select first <max_count>" if there's more than max count images in the folder.

**Comment by jerinamathews** [comment]
Any update on this?

**Comment by nguyenhoanglam** [comment]
@jerinamathews please check out this feature at the latest version!
