### ISSUE TITLE
Can not add request code to ImagePicker

### ISSUE THREAD

**Issue by lalitsharma1607** [nguyenhoanglam/ImagePicker#97]
In `onActivityResult(){...} ` I got Config.RC_PICK_IMAGES which is not settable from Builder. I want to set this as per my need.

**Comment by nguyenhoanglam** [comment]
Just released version 1.3.1 with your requested feature. Please check it out and close this issue.
Thanks!

**Comment by yasserelsayed** [comment]
in my case i want use ImagePicker with old project and i can't upgrade all libraries to support AndroidX  so i have to use ImagePicker 1.2.1 
**so this my solution :**    
 
`
public class ImagePickerBuilderExtended extends ImagePicker.Builder {

    int RequestCode;
    Fragment _Fragment;
    public ImagePickerBuilderExtended(Fragment fragment) {
        super(fragment);

        /// set your Config here
                 this.setCameraOnly(false);               //  Camera mode
                 this.setImageTitle("Galleries") ;        //  Image title (works with FolderMode = false)
                 this.setSavePath("ImagePicker") ;        //  Image capture folder name

                 RequestCode = 100;
                 this._Fragment = fragment;
    }


    public void setRequestCode(int requestCode)
    {
        this.RequestCode = requestCode;
    }

    @Override
    public void start() {
        Intent intent = this.getIntent();
        if (!this.config.isCameraOnly()) {
            this._Fragment.startActivityForResult(intent, RequestCode);
        } else {
            this._Fragment.getActivity().overridePendingTransition(0, 0);
            this._Fragment.startActivityForResult(intent, RequestCode);
        }
    }

    @Override
        public Intent getIntent() {
            Intent intent;
            if (!this.config.isCameraOnly()) {
                intent = new Intent(this._Fragment.getActivity(), ImagePickerActivity.class);
                intent.putExtra("ImagePickerConfig", this.config);
            } else {
                intent = new Intent(this._Fragment.getActivity(), CameraActivty.class);
                intent.putExtra("ImagePickerConfig", this.config);
            }
            return intent;
        }
}
`


**how to call from fragment**
`
 ImagePickerBuilderExtended  _ImagePickerBuilderExtended = new ImagePickerBuilderExtended(this);
     _ImagePickerBuilderExtended.setRequestCode(REQUEST_TAKE_PHOTO);
            _ImagePickerBuilderExtended.start();
`

**Comment by nguyenhoanglam** [comment]
Hi @lalitsharma1607  @yasserelsayed ,
Version 1.4.0 is now available! Please read `What's new` and check if you issue has been fixed!

**Comment by lalitsharma1607** [comment]
Thanks @nguyenhoanglam
